### ISSUE TITLE
Bullet point text too dark in Minimal Markdown with Midnight

### ISSUE THREAD

**Issue by leafcutterant** [standardnotes/midnight-theme#6]
The blue and green used in the Minimal Markdown Editor for bullet points is too dark to work with in the Midnight theme. Especially the blue, but both could use a lighter color (literally, the same color but with the opposite Lightness value in HSL).

Thank you!

![image](https://user-images.githubusercontent.com/7106231/80763866-c276fd80-8b3f-11ea-8a20-847efe24c6cd.png)

**Comment by JaspalSuri** [comment]
Thanks for the feedback; I'll pass this along to the team! (Great username, btw.)

**Comment by leafcutterant** [comment]
Hey, I don't want to seem too pushy, but this is literally killing my eyes. Could you guys do something about it? It would be just changing a few color codes. I can come up with the colors if you're too busy, let me know.

**Comment by JaspalSuri** [comment]
Hi @leafcutterant, sorry for the delayed response. This task has been added to our Extensions dev's todo list.
