### ISSUE TITLE
Hyperlink text color too dark in Markdown Pro and Minimal Markdown editors

### ISSUE THREAD

**Issue by leafcutterant** [standardnotes/midnight-theme#7]
Similar to: #6 

Markdown Pro example:

![image](https://user-images.githubusercontent.com/7106231/99576723-43112480-29d2-11eb-884e-8684363a5a19.png)

Minimal Markdown example:

![image](https://user-images.githubusercontent.com/7106231/99576655-2d9bfa80-29d2-11eb-8bcb-c72e9ee28197.png)

**Comment by JaspalSuri** [comment]
It doesn't appear illegible on my end, but I'll reach out to our users on Slack for their thoughts on it. It wouldn't hurt to make it a bit brighter, but it depends on what everyone is seeing on their screen.

**Comment by jnials** [comment]
Hard for me.  Not enough contrast.  I've abandoned dark themes on SN, and on most things.  I have to dig around to find themes that work.

I'm certain some of this is my "old eyes".
